[project]
name = "mindovermatter"
authors = [
    { name = "Jack Scott", email = "cloner.bl12@gmail.com" }
]
version = "0.3.0"
description = " A Feature-rich Todo CLI, while being local, backed by SQLite"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=14.3.2",
    "tabulate>=0.10.0",
    "typer>=0.21.1",
]
